require('./support/helpers')
require('./support/axios')
require('./store/store.js')
require('./support/core')
require('./support/vue')
require('./support/broadcast')
require('./pages/boostrap')

require('./apps/providers.js')
require('./apps/parties.js')
require('./apps/legislatures.js')
require('./apps/cost_centers.js')
